"""
Financial Domain Training and Test Data for BIRD Framework
"""

from bird_framework import DecisionContext

financial_training_data = [
    ({'age': 42, 'income': 136064, 'net_worth': 131950, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 20, 'current_portfolio': {'stocks': 87, 'bonds': 20, 'cash': 0}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 87, 'bonds_percentage': 20, 'cash_percentage': -7}, "growth-focused strategy"),
    ({'age': 44, 'income': 80281, 'net_worth': 286039, 'risk_tolerance': 'conservative', 'investment_goals': ['children_education'], 'time_horizon': 13, 'current_portfolio': {'stocks': 34, 'bonds': 54, 'cash': 12}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 34, 'bonds_percentage': 54, 'cash_percentage': 12}, "income-focused strategy"),
    ({'age': 41, 'income': 196233, 'net_worth': 460263, 'risk_tolerance': 'moderate', 'investment_goals': ['house_down_payment'], 'time_horizon': 15, 'current_portfolio': {'stocks': 66, 'bonds': 37, 'cash': 0}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 66, 'bonds_percentage': 37, 'cash_percentage': -3}, "income-focused strategy"),
    ({'age': 44, 'income': 109447, 'net_worth': 262902, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement'], 'time_horizon': 22, 'current_portfolio': {'stocks': 84, 'bonds': 7, 'cash': 9}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 84, 'bonds_percentage': 7, 'cash_percentage': 9}, "growth-focused strategy"),
    ({'age': 31, 'income': 94698, 'net_worth': 239736, 'risk_tolerance': 'moderate', 'investment_goals': ['children_education'], 'time_horizon': 13, 'current_portfolio': {'stocks': 57, 'bonds': 23, 'cash': 20}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 57, 'bonds_percentage': 23, 'cash_percentage': 20}, "growth-focused strategy"),
    ({'age': 67, 'income': 229169, 'net_worth': 590042, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 5, 'current_portfolio': {'stocks': 38, 'bonds': 41, 'cash': 21}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 38, 'bonds_percentage': 41, 'cash_percentage': 21}, "income-focused strategy"),
    ({'age': 69, 'income': 81458, 'net_worth': 343603, 'risk_tolerance': 'aggressive', 'investment_goals': ['children_education'], 'time_horizon': 6, 'current_portfolio': {'stocks': 85, 'bonds': 19, 'cash': 0}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 85, 'bonds_percentage': 19, 'cash_percentage': -4}, "income-focused strategy"),
    ({'age': 56, 'income': 497399, 'net_worth': 384532, 'risk_tolerance': 'aggressive', 'investment_goals': ['house_down_payment'], 'time_horizon': 13, 'current_portfolio': {'stocks': 81, 'bonds': 16, 'cash': 3}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 81, 'bonds_percentage': 16, 'cash_percentage': 3}, "growth-focused strategy"),
    ({'age': 43, 'income': 494478, 'net_worth': 741164, 'risk_tolerance': 'moderate', 'investment_goals': ['emergency_fund', 'retirement'], 'time_horizon': 21, 'current_portfolio': {'stocks': 56, 'bonds': 39, 'cash': 5}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 56, 'bonds_percentage': 39, 'cash_percentage': 5}, "growth-focused strategy"),
    ({'age': 52, 'income': 40745, 'net_worth': 193628, 'risk_tolerance': 'moderate', 'investment_goals': ['children_education'], 'time_horizon': 10, 'current_portfolio': {'stocks': 63, 'bonds': 25, 'cash': 12}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 63, 'bonds_percentage': 25, 'cash_percentage': 12}, "income-focused strategy"),
    ({'age': 71, 'income': 90124, 'net_worth': 324574, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 5, 'current_portfolio': {'stocks': 69, 'bonds': 35, 'cash': 0}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'economic recession concerns', 'stocks_percentage': 69, 'bonds_percentage': 35, 'cash_percentage': -4}, "income-focused strategy"),
    ({'age': 71, 'income': 47732, 'net_worth': 39661, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 5, 'current_portfolio': {'stocks': 33, 'bonds': 45, 'cash': 22}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'economic recession concerns', 'stocks_percentage': 33, 'bonds_percentage': 45, 'cash_percentage': 22}, "income-focused strategy"),
    ({'age': 44, 'income': 49217, 'net_worth': 171824, 'risk_tolerance': 'aggressive', 'investment_goals': ['children_education'], 'time_horizon': 13, 'current_portfolio': {'stocks': 83, 'bonds': 16, 'cash': 1}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 83, 'bonds_percentage': 16, 'cash_percentage': 1}, "growth-focused strategy"),
    ({'age': 79, 'income': 111551, 'net_worth': 284737, 'risk_tolerance': 'conservative', 'investment_goals': ['house_down_payment'], 'time_horizon': 9, 'current_portfolio': {'stocks': 32, 'bonds': 56, 'cash': 12}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 32, 'bonds_percentage': 56, 'cash_percentage': 12}, "income-focused strategy"),
    ({'age': 62, 'income': 60923, 'net_worth': 207204, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 8, 'current_portfolio': {'stocks': 55, 'bonds': 39, 'cash': 6}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 55, 'bonds_percentage': 39, 'cash_percentage': 6}, "income-focused strategy"),
    ({'age': 74, 'income': 111368, 'net_worth': 265836, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement'], 'time_horizon': 5, 'current_portfolio': {'stocks': 85, 'bonds': 15, 'cash': 0}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'economic recession concerns', 'stocks_percentage': 85, 'bonds_percentage': 15, 'cash_percentage': 0}, "income-focused strategy"),
    ({'age': 47, 'income': 79088, 'net_worth': 264588, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 18, 'current_portfolio': {'stocks': 38, 'bonds': 53, 'cash': 9}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'economic recession concerns', 'stocks_percentage': 38, 'bonds_percentage': 53, 'cash_percentage': 9}, "income-focused strategy"),
    ({'age': 51, 'income': 85903, 'net_worth': 357169, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement'], 'time_horizon': 12, 'current_portfolio': {'stocks': 50, 'bonds': 46, 'cash': 4}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'economic recession concerns', 'stocks_percentage': 50, 'bonds_percentage': 46, 'cash_percentage': 4}, "income-focused strategy"),
    ({'age': 33, 'income': 39340, 'net_worth': 41657, 'risk_tolerance': 'conservative', 'investment_goals': ['children_education'], 'time_horizon': 10, 'current_portfolio': {'stocks': 24, 'bonds': 66, 'cash': 10}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 24, 'bonds_percentage': 66, 'cash_percentage': 10}, "income-focused strategy"),
    ({'age': 33, 'income': 45605, 'net_worth': 140314, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 36, 'current_portfolio': {'stocks': 64, 'bonds': 36, 'cash': 0}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'economic recession concerns', 'stocks_percentage': 64, 'bonds_percentage': 36, 'cash_percentage': 0}, "growth-focused strategy"),
    ({'age': 79, 'income': 332809, 'net_worth': 243203, 'risk_tolerance': 'aggressive', 'investment_goals': ['house_down_payment'], 'time_horizon': 7, 'current_portfolio': {'stocks': 71, 'bonds': 15, 'cash': 14}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 71, 'bonds_percentage': 15, 'cash_percentage': 14}, "income-focused strategy"),
    ({'age': 71, 'income': 43126, 'net_worth': 34973, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 5, 'current_portfolio': {'stocks': 87, 'bonds': 14, 'cash': 0}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 87, 'bonds_percentage': 14, 'cash_percentage': -1}, "income-focused strategy"),
    ({'age': 27, 'income': 40171, 'net_worth': 141128, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement'], 'time_horizon': 33, 'current_portfolio': {'stocks': 59, 'bonds': 22, 'cash': 19}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 59, 'bonds_percentage': 22, 'cash_percentage': 19}, "growth-focused strategy"),
    ({'age': 67, 'income': 57416, 'net_worth': 265986, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 5, 'current_portfolio': {'stocks': 70, 'bonds': 36, 'cash': 0}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 70, 'bonds_percentage': 36, 'cash_percentage': -6}, "income-focused strategy"),
    ({'age': 53, 'income': 41544, 'net_worth': 163906, 'risk_tolerance': 'moderate', 'investment_goals': ['emergency_fund', 'retirement'], 'time_horizon': 17, 'current_portfolio': {'stocks': 64, 'bonds': 35, 'cash': 1}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'economic recession concerns', 'stocks_percentage': 64, 'bonds_percentage': 35, 'cash_percentage': 1}, "income-focused strategy"),
    ({'age': 53, 'income': 180534, 'net_worth': 649659, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 17, 'current_portfolio': {'stocks': 38, 'bonds': 70, 'cash': 0}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 38, 'bonds_percentage': 70, 'cash_percentage': -8}, "income-focused strategy"),
    ({'age': 63, 'income': 173116, 'net_worth': 469924, 'risk_tolerance': 'conservative', 'investment_goals': ['house_down_payment'], 'time_horizon': 12, 'current_portfolio': {'stocks': 32, 'bonds': 56, 'cash': 12}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 32, 'bonds_percentage': 56, 'cash_percentage': 12}, "income-focused strategy"),
    ({'age': 41, 'income': 137079, 'net_worth': 474774, 'risk_tolerance': 'moderate', 'investment_goals': ['emergency_fund', 'retirement'], 'time_horizon': 24, 'current_portfolio': {'stocks': 51, 'bonds': 40, 'cash': 9}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 51, 'bonds_percentage': 40, 'cash_percentage': 9}, "income-focused strategy"),
    ({'age': 49, 'income': 62069, 'net_worth': 88650, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement'], 'time_horizon': 18, 'current_portfolio': {'stocks': 33, 'bonds': 44, 'cash': 23}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 33, 'bonds_percentage': 44, 'cash_percentage': 23}, "income-focused strategy"),
    ({'age': 57, 'income': 48432, 'net_worth': 82221, 'risk_tolerance': 'aggressive', 'investment_goals': ['house_down_payment'], 'time_horizon': 3, 'current_portfolio': {'stocks': 87, 'bonds': 18, 'cash': 0}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 87, 'bonds_percentage': 18, 'cash_percentage': -5}, "growth-focused strategy"),
    ({'age': 62, 'income': 64071, 'net_worth': 94018, 'risk_tolerance': 'moderate', 'investment_goals': ['children_education'], 'time_horizon': 5, 'current_portfolio': {'stocks': 66, 'bonds': 29, 'cash': 5}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 66, 'bonds_percentage': 29, 'cash_percentage': 5}, "income-focused strategy"),
    ({'age': 57, 'income': 159469, 'net_worth': 609842, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 5, 'current_portfolio': {'stocks': 90, 'bonds': 11, 'cash': 0}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 90, 'bonds_percentage': 11, 'cash_percentage': -1}, "growth-focused strategy"),
    ({'age': 49, 'income': 139739, 'net_worth': 85947, 'risk_tolerance': 'conservative', 'investment_goals': ['house_down_payment'], 'time_horizon': 14, 'current_portfolio': {'stocks': 43, 'bonds': 64, 'cash': 0}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 43, 'bonds_percentage': 64, 'cash_percentage': -7}, "income-focused strategy"),
    ({'age': 74, 'income': 320410, 'net_worth': 679275, 'risk_tolerance': 'moderate', 'investment_goals': ['children_education'], 'time_horizon': 5, 'current_portfolio': {'stocks': 56, 'bonds': 23, 'cash': 21}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 56, 'bonds_percentage': 23, 'cash_percentage': 21}, "income-focused strategy"),
    ({'age': 30, 'income': 57494, 'net_worth': 250703, 'risk_tolerance': 'conservative', 'investment_goals': ['emergency_fund', 'retirement'], 'time_horizon': 40, 'current_portfolio': {'stocks': 44, 'bonds': 40, 'cash': 16}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 44, 'bonds_percentage': 40, 'cash_percentage': 16}, "growth-focused strategy"),
    ({'age': 64, 'income': 115058, 'net_worth': 457353, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 5, 'current_portfolio': {'stocks': 67, 'bonds': 39, 'cash': 0}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 67, 'bonds_percentage': 39, 'cash_percentage': -6}, "income-focused strategy"),
    ({'age': 44, 'income': 258293, 'net_worth': 733338, 'risk_tolerance': 'conservative', 'investment_goals': ['children_education'], 'time_horizon': 4, 'current_portfolio': {'stocks': 27, 'bonds': 53, 'cash': 20}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 27, 'bonds_percentage': 53, 'cash_percentage': 20}, "income-focused strategy"),
    ({'age': 79, 'income': 42070, 'net_worth': 107867, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement'], 'time_horizon': 5, 'current_portfolio': {'stocks': 79, 'bonds': 5, 'cash': 16}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 79, 'bonds_percentage': 5, 'cash_percentage': 16}, "income-focused strategy"),
    ({'age': 78, 'income': 76217, 'net_worth': 350486, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 5, 'current_portfolio': {'stocks': 42, 'bonds': 51, 'cash': 7}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 42, 'bonds_percentage': 51, 'cash_percentage': 7}, "income-focused strategy"),
    ({'age': 49, 'income': 175690, 'net_worth': 714807, 'risk_tolerance': 'aggressive', 'investment_goals': ['emergency_fund', 'retirement'], 'time_horizon': 16, 'current_portfolio': {'stocks': 79, 'bonds': 9, 'cash': 12}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 79, 'bonds_percentage': 9, 'cash_percentage': 12}, "growth-focused strategy"),
    ({'age': 30, 'income': 139315, 'net_worth': 234813, 'risk_tolerance': 'aggressive', 'investment_goals': ['wealth_building', 'retirement'], 'time_horizon': 40, 'current_portfolio': {'stocks': 81, 'bonds': 12, 'cash': 7}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 81, 'bonds_percentage': 12, 'cash_percentage': 7}, "growth-focused strategy"),
    ({'age': 55, 'income': 115726, 'net_worth': 61915, 'risk_tolerance': 'moderate', 'investment_goals': ['wealth_building', 'retirement'], 'time_horizon': 11, 'current_portfolio': {'stocks': 54, 'bonds': 32, 'cash': 14}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 54, 'bonds_percentage': 32, 'cash_percentage': 14}, "income-focused strategy"),
    ({'age': 41, 'income': 82676, 'net_worth': 313389, 'risk_tolerance': 'moderate', 'investment_goals': ['emergency_fund', 'retirement'], 'time_horizon': 20, 'current_portfolio': {'stocks': 56, 'bonds': 40, 'cash': 4}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 56, 'bonds_percentage': 40, 'cash_percentage': 4}, "growth-focused strategy"),
    ({'age': 53, 'income': 356884, 'net_worth': 1423572, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 15, 'current_portfolio': {'stocks': 65, 'bonds': 38, 'cash': 0}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 65, 'bonds_percentage': 38, 'cash_percentage': -3}, "income-focused strategy"),
    ({'age': 61, 'income': 474969, 'net_worth': 1574353, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 5, 'current_portfolio': {'stocks': 79, 'bonds': 17, 'cash': 4}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'economic recession concerns', 'stocks_percentage': 79, 'bonds_percentage': 17, 'cash_percentage': 4}, "income-focused strategy"),
    ({'age': 46, 'income': 63440, 'net_worth': 84252, 'risk_tolerance': 'moderate', 'investment_goals': ['children_education'], 'time_horizon': 14, 'current_portfolio': {'stocks': 53, 'bonds': 24, 'cash': 23}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 53, 'bonds_percentage': 24, 'cash_percentage': 23}, "income-focused strategy"),
    ({'age': 67, 'income': 193626, 'net_worth': 185238, 'risk_tolerance': 'aggressive', 'investment_goals': ['wealth_building', 'retirement'], 'time_horizon': 5, 'current_portfolio': {'stocks': 77, 'bonds': 19, 'cash': 4}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 77, 'bonds_percentage': 19, 'cash_percentage': 4}, "income-focused strategy"),
    ({'age': 24, 'income': 477265, 'net_worth': 772764, 'risk_tolerance': 'aggressive', 'investment_goals': ['house_down_payment'], 'time_horizon': 3, 'current_portfolio': {'stocks': 79, 'bonds': 19, 'cash': 2}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 79, 'bonds_percentage': 19, 'cash_percentage': 2}, "growth-focused strategy"),
    ({'age': 40, 'income': 129473, 'net_worth': 376807, 'risk_tolerance': 'moderate', 'investment_goals': ['wealth_building', 'retirement'], 'time_horizon': 23, 'current_portfolio': {'stocks': 60, 'bonds': 35, 'cash': 5}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 60, 'bonds_percentage': 35, 'cash_percentage': 5}, "growth-focused strategy"),
    ({'age': 22, 'income': 81826, 'net_worth': 289291, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 40, 'current_portfolio': {'stocks': 86, 'bonds': 9, 'cash': 5}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 86, 'bonds_percentage': 9, 'cash_percentage': 5}, "growth-focused strategy"),
    ({'age': 27, 'income': 61847, 'net_worth': 198005, 'risk_tolerance': 'conservative', 'investment_goals': ['emergency_fund', 'retirement'], 'time_horizon': 43, 'current_portfolio': {'stocks': 45, 'bonds': 44, 'cash': 11}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'economic recession concerns', 'stocks_percentage': 45, 'bonds_percentage': 44, 'cash_percentage': 11}, "income-focused strategy"),
    ({'age': 36, 'income': 149436, 'net_worth': 709074, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement'], 'time_horizon': 25, 'current_portfolio': {'stocks': 88, 'bonds': 11, 'cash': 1}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 88, 'bonds_percentage': 11, 'cash_percentage': 1}, "growth-focused strategy"),
    ({'age': 70, 'income': 63365, 'net_worth': 283575, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 5, 'current_portfolio': {'stocks': 44, 'bonds': 66, 'cash': 0}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 44, 'bonds_percentage': 66, 'cash_percentage': -10}, "income-focused strategy"),
    ({'age': 50, 'income': 146019, 'net_worth': 227873, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement'], 'time_horizon': 12, 'current_portfolio': {'stocks': 26, 'bonds': 45, 'cash': 29}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 26, 'bonds_percentage': 45, 'cash_percentage': 29}, "income-focused strategy"),
    ({'age': 65, 'income': 117992, 'net_worth': 173528, 'risk_tolerance': 'aggressive', 'investment_goals': ['wealth_building', 'retirement'], 'time_horizon': 5, 'current_portfolio': {'stocks': 77, 'bonds': 6, 'cash': 17}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 77, 'bonds_percentage': 6, 'cash_percentage': 17}, "income-focused strategy"),
    ({'age': 49, 'income': 64454, 'net_worth': 111410, 'risk_tolerance': 'conservative', 'investment_goals': ['house_down_payment'], 'time_horizon': 11, 'current_portfolio': {'stocks': 31, 'bonds': 41, 'cash': 28}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 31, 'bonds_percentage': 41, 'cash_percentage': 28}, "income-focused strategy"),
    ({'age': 56, 'income': 74360, 'net_worth': 107208, 'risk_tolerance': 'moderate', 'investment_goals': ['house_down_payment'], 'time_horizon': 10, 'current_portfolio': {'stocks': 61, 'bonds': 33, 'cash': 6}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 61, 'bonds_percentage': 33, 'cash_percentage': 6}, "income-focused strategy"),
    ({'age': 76, 'income': 208247, 'net_worth': 111056, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 5, 'current_portfolio': {'stocks': 70, 'bonds': 13, 'cash': 17}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 70, 'bonds_percentage': 13, 'cash_percentage': 17}, "income-focused strategy"),
    ({'age': 58, 'income': 52564, 'net_worth': 41987, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 8, 'current_portfolio': {'stocks': 34, 'bonds': 46, 'cash': 20}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 34, 'bonds_percentage': 46, 'cash_percentage': 20}, "income-focused strategy"),
    ({'age': 48, 'income': 75514, 'net_worth': 296766, 'risk_tolerance': 'conservative', 'investment_goals': ['children_education'], 'time_horizon': 11, 'current_portfolio': {'stocks': 31, 'bonds': 54, 'cash': 15}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 31, 'bonds_percentage': 54, 'cash_percentage': 15}, "income-focused strategy"),
    ({'age': 75, 'income': 418991, 'net_worth': 816652, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 5, 'current_portfolio': {'stocks': 25, 'bonds': 65, 'cash': 10}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 25, 'bonds_percentage': 65, 'cash_percentage': 10}, "income-focused strategy"),
    ({'age': 24, 'income': 184192, 'net_worth': 169863, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 46, 'current_portfolio': {'stocks': 61, 'bonds': 24, 'cash': 15}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 61, 'bonds_percentage': 24, 'cash_percentage': 15}, "growth-focused strategy"),
    ({'age': 32, 'income': 395717, 'net_worth': 729801, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement'], 'time_horizon': 33, 'current_portfolio': {'stocks': 81, 'bonds': 12, 'cash': 7}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 81, 'bonds_percentage': 12, 'cash_percentage': 7}, "growth-focused strategy"),
    ({'age': 31, 'income': 103794, 'net_worth': 146486, 'risk_tolerance': 'moderate', 'investment_goals': ['wealth_building', 'retirement'], 'time_horizon': 33, 'current_portfolio': {'stocks': 61, 'bonds': 20, 'cash': 19}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'economic recession concerns', 'stocks_percentage': 61, 'bonds_percentage': 20, 'cash_percentage': 19}, "growth-focused strategy"),
    ({'age': 58, 'income': 32950, 'net_worth': 119561, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 5, 'current_portfolio': {'stocks': 88, 'bonds': 16, 'cash': 0}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 88, 'bonds_percentage': 16, 'cash_percentage': -4}, "income-focused strategy"),
    ({'age': 71, 'income': 435162, 'net_worth': 2041306, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 5, 'current_portfolio': {'stocks': 54, 'bonds': 40, 'cash': 6}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 54, 'bonds_percentage': 40, 'cash_percentage': 6}, "income-focused strategy"),
    ({'age': 77, 'income': 441607, 'net_worth': 573614, 'risk_tolerance': 'aggressive', 'investment_goals': ['emergency_fund', 'retirement'], 'time_horizon': 5, 'current_portfolio': {'stocks': 74, 'bonds': 20, 'cash': 6}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'economic recession concerns', 'stocks_percentage': 74, 'bonds_percentage': 20, 'cash_percentage': 6}, "income-focused strategy"),
    ({'age': 27, 'income': 48283, 'net_worth': 201974, 'risk_tolerance': 'moderate', 'investment_goals': ['children_education'], 'time_horizon': 7, 'current_portfolio': {'stocks': 54, 'bonds': 30, 'cash': 16}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 54, 'bonds_percentage': 30, 'cash_percentage': 16}, "income-focused strategy"),
    ({'age': 46, 'income': 51168, 'net_worth': 201340, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 19, 'current_portfolio': {'stocks': 61, 'bonds': 29, 'cash': 10}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'economic recession concerns', 'stocks_percentage': 61, 'bonds_percentage': 29, 'cash_percentage': 10}, "growth-focused strategy"),
    ({'age': 56, 'income': 91081, 'net_worth': 80737, 'risk_tolerance': 'conservative', 'investment_goals': ['emergency_fund', 'retirement'], 'time_horizon': 5, 'current_portfolio': {'stocks': 33, 'bonds': 43, 'cash': 24}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 33, 'bonds_percentage': 43, 'cash_percentage': 24}, "income-focused strategy"),
    ({'age': 47, 'income': 85993, 'net_worth': 168474, 'risk_tolerance': 'aggressive', 'investment_goals': ['children_education'], 'time_horizon': 15, 'current_portfolio': {'stocks': 82, 'bonds': 19, 'cash': 0}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 82, 'bonds_percentage': 19, 'cash_percentage': -1}, "growth-focused strategy"),
    ({'age': 42, 'income': 76711, 'net_worth': 144962, 'risk_tolerance': 'moderate', 'investment_goals': ['wealth_building', 'retirement'], 'time_horizon': 19, 'current_portfolio': {'stocks': 61, 'bonds': 22, 'cash': 17}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 61, 'bonds_percentage': 22, 'cash_percentage': 17}, "growth-focused strategy"),
    ({'age': 30, 'income': 108870, 'net_worth': 330241, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 38, 'current_portfolio': {'stocks': 70, 'bonds': 17, 'cash': 13}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 70, 'bonds_percentage': 17, 'cash_percentage': 13}, "growth-focused strategy"),
    ({'age': 55, 'income': 147139, 'net_worth': 611296, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 6, 'current_portfolio': {'stocks': 60, 'bonds': 26, 'cash': 14}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 60, 'bonds_percentage': 26, 'cash_percentage': 14}, "growth-focused strategy"),
    ({'age': 38, 'income': 173874, 'net_worth': 130132, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement'], 'time_horizon': 22, 'current_portfolio': {'stocks': 28, 'bonds': 60, 'cash': 12}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'economic recession concerns', 'stocks_percentage': 28, 'bonds_percentage': 60, 'cash_percentage': 12}, "income-focused strategy"),
    ({'age': 78, 'income': 297680, 'net_worth': 755896, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement'], 'time_horizon': 5, 'current_portfolio': {'stocks': 39, 'bonds': 43, 'cash': 18}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 39, 'bonds_percentage': 43, 'cash_percentage': 18}, "income-focused strategy"),
    ({'age': 48, 'income': 35804, 'net_worth': 147431, 'risk_tolerance': 'moderate', 'investment_goals': ['emergency_fund', 'retirement'], 'time_horizon': 21, 'current_portfolio': {'stocks': 64, 'bonds': 38, 'cash': 0}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 64, 'bonds_percentage': 38, 'cash_percentage': -2}, "income-focused strategy"),
    ({'age': 33, 'income': 160036, 'net_worth': 754609, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement'], 'time_horizon': 34, 'current_portfolio': {'stocks': 33, 'bonds': 61, 'cash': 6}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 33, 'bonds_percentage': 61, 'cash_percentage': 6}, "growth-focused strategy"),
    ({'age': 26, 'income': 146090, 'net_worth': 181678, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 37, 'current_portfolio': {'stocks': 85, 'bonds': 12, 'cash': 3}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 85, 'bonds_percentage': 12, 'cash_percentage': 3}, "growth-focused strategy"),
    ({'age': 48, 'income': 88352, 'net_worth': 307821, 'risk_tolerance': 'conservative', 'investment_goals': ['emergency_fund', 'retirement'], 'time_horizon': 13, 'current_portfolio': {'stocks': 24, 'bonds': 49, 'cash': 27}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'economic recession concerns', 'stocks_percentage': 24, 'bonds_percentage': 49, 'cash_percentage': 27}, "income-focused strategy"),
    ({'age': 26, 'income': 446723, 'net_worth': 822618, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement'], 'time_horizon': 35, 'current_portfolio': {'stocks': 74, 'bonds': 13, 'cash': 13}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 74, 'bonds_percentage': 13, 'cash_percentage': 13}, "growth-focused strategy"),
    ({'age': 55, 'income': 48791, 'net_worth': 201767, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 11, 'current_portfolio': {'stocks': 74, 'bonds': 14, 'cash': 12}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 74, 'bonds_percentage': 14, 'cash_percentage': 12}, "growth-focused strategy"),
    ({'age': 65, 'income': 110828, 'net_worth': 436614, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement'], 'time_horizon': 5, 'current_portfolio': {'stocks': 55, 'bonds': 37, 'cash': 8}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 55, 'bonds_percentage': 37, 'cash_percentage': 8}, "income-focused strategy"),
    ({'age': 22, 'income': 97532, 'net_worth': 330130, 'risk_tolerance': 'conservative', 'investment_goals': ['house_down_payment'], 'time_horizon': 8, 'current_portfolio': {'stocks': 34, 'bonds': 43, 'cash': 23}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'economic recession concerns', 'stocks_percentage': 34, 'bonds_percentage': 43, 'cash_percentage': 23}, "income-focused strategy"),
    ({'age': 73, 'income': 120631, 'net_worth': 448343, 'risk_tolerance': 'moderate', 'investment_goals': ['wealth_building', 'retirement'], 'time_horizon': 5, 'current_portfolio': {'stocks': 69, 'bonds': 22, 'cash': 9}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 69, 'bonds_percentage': 22, 'cash_percentage': 9}, "income-focused strategy"),
    ({'age': 80, 'income': 87119, 'net_worth': 221256, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 5, 'current_portfolio': {'stocks': 60, 'bonds': 33, 'cash': 7}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 60, 'bonds_percentage': 33, 'cash_percentage': 7}, "income-focused strategy"),
    ({'age': 26, 'income': 323480, 'net_worth': 1098612, 'risk_tolerance': 'moderate', 'investment_goals': ['children_education'], 'time_horizon': 7, 'current_portfolio': {'stocks': 68, 'bonds': 20, 'cash': 12}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 68, 'bonds_percentage': 20, 'cash_percentage': 12}, "growth-focused strategy"),
    ({'age': 62, 'income': 41349, 'net_worth': 136640, 'risk_tolerance': 'aggressive', 'investment_goals': ['children_education'], 'time_horizon': 14, 'current_portfolio': {'stocks': 76, 'bonds': 11, 'cash': 13}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 76, 'bonds_percentage': 11, 'cash_percentage': 13}, "growth-focused strategy"),
    ({'age': 76, 'income': 194801, 'net_worth': 120227, 'risk_tolerance': 'moderate', 'investment_goals': ['children_education'], 'time_horizon': 3, 'current_portfolio': {'stocks': 68, 'bonds': 22, 'cash': 10}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 68, 'bonds_percentage': 22, 'cash_percentage': 10}, "income-focused strategy"),
    ({'age': 32, 'income': 95071, 'net_worth': 434819, 'risk_tolerance': 'aggressive', 'investment_goals': ['emergency_fund', 'retirement'], 'time_horizon': 28, 'current_portfolio': {'stocks': 83, 'bonds': 10, 'cash': 7}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 83, 'bonds_percentage': 10, 'cash_percentage': 7}, "growth-focused strategy"),
    ({'age': 26, 'income': 272767, 'net_worth': 1120178, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 34, 'current_portfolio': {'stocks': 50, 'bonds': 28, 'cash': 22}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'economic recession concerns', 'stocks_percentage': 50, 'bonds_percentage': 28, 'cash_percentage': 22}, "growth-focused strategy"),
    ({'age': 50, 'income': 140662, 'net_worth': 481328, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 11, 'current_portfolio': {'stocks': 37, 'bonds': 52, 'cash': 11}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 37, 'bonds_percentage': 52, 'cash_percentage': 11}, "income-focused strategy"),
    ({'age': 39, 'income': 130149, 'net_worth': 463364, 'risk_tolerance': 'aggressive', 'investment_goals': ['emergency_fund', 'retirement'], 'time_horizon': 24, 'current_portfolio': {'stocks': 87, 'bonds': 15, 'cash': 0}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 87, 'bonds_percentage': 15, 'cash_percentage': -2}, "growth-focused strategy"),
    ({'age': 32, 'income': 181006, 'net_worth': 227917, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 30, 'current_portfolio': {'stocks': 75, 'bonds': 10, 'cash': 15}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 75, 'bonds_percentage': 10, 'cash_percentage': 15}, "growth-focused strategy"),
    ({'age': 74, 'income': 488283, 'net_worth': 1417374, 'risk_tolerance': 'aggressive', 'investment_goals': ['wealth_building', 'retirement'], 'time_horizon': 5, 'current_portfolio': {'stocks': 74, 'bonds': 8, 'cash': 18}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 74, 'bonds_percentage': 8, 'cash_percentage': 18}, "income-focused strategy"),
    ({'age': 45, 'income': 32154, 'net_worth': 97155, 'risk_tolerance': 'moderate', 'investment_goals': ['wealth_building', 'retirement'], 'time_horizon': 22, 'current_portfolio': {'stocks': 63, 'bonds': 33, 'cash': 4}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 63, 'bonds_percentage': 33, 'cash_percentage': 4}, "growth-focused strategy"),
    ({'age': 71, 'income': 62040, 'net_worth': 105877, 'risk_tolerance': 'aggressive', 'investment_goals': ['wealth_building', 'retirement'], 'time_horizon': 5, 'current_portfolio': {'stocks': 74, 'bonds': 7, 'cash': 19}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'economic recession concerns', 'stocks_percentage': 74, 'bonds_percentage': 7, 'cash_percentage': 19}, "income-focused strategy"),
    ({'age': 34, 'income': 157272, 'net_worth': 498089, 'risk_tolerance': 'aggressive', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 32, 'current_portfolio': {'stocks': 75, 'bonds': 20, 'cash': 5}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 75, 'bonds_percentage': 20, 'cash_percentage': 5}, "growth-focused strategy"),
    ({'age': 45, 'income': 236482, 'net_worth': 415773, 'risk_tolerance': 'aggressive', 'investment_goals': ['wealth_building', 'retirement'], 'time_horizon': 15, 'current_portfolio': {'stocks': 86, 'bonds': 11, 'cash': 3}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 86, 'bonds_percentage': 11, 'cash_percentage': 3}, "growth-focused strategy"),
    ({'age': 58, 'income': 53816, 'net_worth': 254983, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 8, 'current_portfolio': {'stocks': 70, 'bonds': 21, 'cash': 9}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 70, 'bonds_percentage': 21, 'cash_percentage': 9}, "income-focused strategy"),
]

financial_test_data = [
    ({'age': 74, 'income': 284965, 'net_worth': 561278, 'risk_tolerance': 'aggressive', 'investment_goals': ['house_down_payment'], 'time_horizon': 7, 'current_portfolio': {'stocks': 90, 'bonds': 20, 'cash': 0}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 90, 'bonds_percentage': 20, 'cash_percentage': -10}, "growth-focused strategy"),
    ({'age': 37, 'income': 219390, 'net_worth': 417391, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement'], 'time_horizon': 26, 'current_portfolio': {'stocks': 30, 'bonds': 69, 'cash': 1}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 30, 'bonds_percentage': 69, 'cash_percentage': 1}, "growth-focused strategy"),
    ({'age': 28, 'income': 188652, 'net_worth': 848866, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 41, 'current_portfolio': {'stocks': 44, 'bonds': 63, 'cash': 0}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 44, 'bonds_percentage': 63, 'cash_percentage': -7}, "growth-focused strategy"),
    ({'age': 69, 'income': 79709, 'net_worth': 115535, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement'], 'time_horizon': 5, 'current_portfolio': {'stocks': 63, 'bonds': 37, 'cash': 0}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 63, 'bonds_percentage': 37, 'cash_percentage': 0}, "income-focused strategy"),
    ({'age': 42, 'income': 232653, 'net_worth': 856384, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 21, 'current_portfolio': {'stocks': 30, 'bonds': 61, 'cash': 9}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 30, 'bonds_percentage': 61, 'cash_percentage': 9}, "income-focused strategy"),
    ({'age': 73, 'income': 44736, 'net_worth': 172224, 'risk_tolerance': 'aggressive', 'investment_goals': ['house_down_payment'], 'time_horizon': 8, 'current_portfolio': {'stocks': 85, 'bonds': 9, 'cash': 6}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 85, 'bonds_percentage': 9, 'cash_percentage': 6}, "income-focused strategy"),
    ({'age': 41, 'income': 300666, 'net_worth': 625428, 'risk_tolerance': 'conservative', 'investment_goals': ['house_down_payment'], 'time_horizon': 4, 'current_portfolio': {'stocks': 47, 'bonds': 65, 'cash': 0}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 47, 'bonds_percentage': 65, 'cash_percentage': -12}, "income-focused strategy"),
    ({'age': 79, 'income': 197754, 'net_worth': 454882, 'risk_tolerance': 'conservative', 'investment_goals': ['children_education'], 'time_horizon': 15, 'current_portfolio': {'stocks': 22, 'bonds': 56, 'cash': 22}, 'market_conditions': 'bear market with high volatility', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 22, 'bonds_percentage': 56, 'cash_percentage': 22}, "income-focused strategy"),
    ({'age': 54, 'income': 264236, 'net_worth': 693046, 'risk_tolerance': 'moderate', 'investment_goals': ['house_down_payment'], 'time_horizon': 5, 'current_portfolio': {'stocks': 51, 'bonds': 29, 'cash': 20}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 51, 'bonds_percentage': 29, 'cash_percentage': 20}, "growth-focused strategy"),
    ({'age': 38, 'income': 52084, 'net_worth': 47428, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 32, 'current_portfolio': {'stocks': 65, 'bonds': 39, 'cash': 0}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 65, 'bonds_percentage': 39, 'cash_percentage': -4}, "growth-focused strategy"),
    ({'age': 70, 'income': 93577, 'net_worth': 106461, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 5, 'current_portfolio': {'stocks': 68, 'bonds': 35, 'cash': 0}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 68, 'bonds_percentage': 35, 'cash_percentage': -3}, "income-focused strategy"),
    ({'age': 64, 'income': 119786, 'net_worth': 521017, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement', 'house_down_payment'], 'time_horizon': 5, 'current_portfolio': {'stocks': 45, 'bonds': 48, 'cash': 7}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 45, 'bonds_percentage': 48, 'cash_percentage': 7}, "income-focused strategy"),
    ({'age': 75, 'income': 37886, 'net_worth': 72966, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement'], 'time_horizon': 5, 'current_portfolio': {'stocks': 34, 'bonds': 59, 'cash': 7}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 34, 'bonds_percentage': 59, 'cash_percentage': 7}, "income-focused strategy"),
    ({'age': 69, 'income': 34447, 'net_worth': 36635, 'risk_tolerance': 'moderate', 'investment_goals': ['house_down_payment'], 'time_horizon': 14, 'current_portfolio': {'stocks': 52, 'bonds': 30, 'cash': 18}, 'market_conditions': 'recovering market after downturn', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 52, 'bonds_percentage': 30, 'cash_percentage': 18}, "income-focused strategy"),
    ({'age': 42, 'income': 450320, 'net_worth': 1589438, 'risk_tolerance': 'conservative', 'investment_goals': ['emergency_fund', 'retirement'], 'time_horizon': 22, 'current_portfolio': {'stocks': 29, 'bonds': 60, 'cash': 11}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'market volatility is increasing', 'stocks_percentage': 29, 'bonds_percentage': 60, 'cash_percentage': 11}, "income-focused strategy"),
    ({'age': 58, 'income': 270359, 'net_worth': 1192589, 'risk_tolerance': 'moderate', 'investment_goals': ['children_education'], 'time_horizon': 6, 'current_portfolio': {'stocks': 60, 'bonds': 25, 'cash': 15}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 60, 'bonds_percentage': 25, 'cash_percentage': 15}, "growth-focused strategy"),
    ({'age': 47, 'income': 43181, 'net_worth': 136661, 'risk_tolerance': 'conservative', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 16, 'current_portfolio': {'stocks': 24, 'bonds': 56, 'cash': 20}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'inflation is rising rapidly', 'stocks_percentage': 24, 'bonds_percentage': 56, 'cash_percentage': 20}, "income-focused strategy"),
    ({'age': 75, 'income': 46319, 'net_worth': 187566, 'risk_tolerance': 'aggressive', 'investment_goals': ['children_education'], 'time_horizon': 13, 'current_portfolio': {'stocks': 85, 'bonds': 12, 'cash': 3}, 'market_conditions': 'sideways market with uncertainty', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 85, 'bonds_percentage': 12, 'cash_percentage': 3}, "income-focused strategy"),
    ({'age': 77, 'income': 238530, 'net_worth': 288694, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement', 'children_education'], 'time_horizon': 5, 'current_portfolio': {'stocks': 54, 'bonds': 28, 'cash': 18}, 'market_conditions': 'bull market with low volatility', 'current_condition': 'geopolitical tensions affecting markets', 'stocks_percentage': 54, 'bonds_percentage': 28, 'cash_percentage': 18}, "income-focused strategy"),
    ({'age': 25, 'income': 383283, 'net_worth': 247572, 'risk_tolerance': 'moderate', 'investment_goals': ['retirement'], 'time_horizon': 41, 'current_portfolio': {'stocks': 61, 'bonds': 27, 'cash': 12}, 'market_conditions': 'volatile market with inflation concerns', 'current_condition': 'interest rates are climbing', 'stocks_percentage': 61, 'bonds_percentage': 27, 'cash_percentage': 12}, "growth-focused strategy"),
]

def get_financial_training_data():
    """Get financial training data as list of (factors_dict, outcome) tuples."""
    return financial_training_data

def get_financial_test_data():
    """Get financial test data as list of (factors_dict, outcome) tuples."""
    return financial_test_data

def convert_to_decision_contexts(data_list):
    """Convert factor dictionaries to DecisionContext objects."""
    contexts = []
    for factors, outcome in data_list:
        # Create scenario and condition from factors
        scenario = "Decision scenario based on provided factors"
        condition = "Condition derived from factor values"
        outcomes = ["conservative treatment", "aggressive treatment"] if "financial" == "medical" else \
                  ["growth-focused strategy", "income-focused strategy"] if "financial" == "financial" else \
                  ["personalized recommendations", "trending recommendations"]
        
        context = DecisionContext(
            scenario=scenario,
            condition=condition,
            outcomes=outcomes
        )
        contexts.append((context, outcome))
    return contexts
