"""
Medical Domain Training and Test Data for BIRD Framework
"""

from bird_framework import DecisionContext

medical_training_data = [
    ({'age': 50, 'gender': 'male', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': ['arthritis'], 'vital_signs': {'blood_pressure': '143/81', 'heart_rate': 119, 'temperature': 100.9}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 143, 'heart_rate': 119, 'temperature': 100.9}, "aggressive treatment"),
    ({'age': 83, 'gender': 'male', 'symptoms': ['back pain', 'muscle stiffness'], 'medical_history': ['heart disease'], 'vital_signs': {'blood_pressure': '124/87', 'heart_rate': 91, 'temperature': 97.1}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 124, 'heart_rate': 91, 'temperature': 97.1}, "aggressive treatment"),
    ({'age': 58, 'gender': 'male', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': ['depression'], 'vital_signs': {'blood_pressure': '129/75', 'heart_rate': 63, 'temperature': 98.2}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 129, 'heart_rate': 63, 'temperature': 98.2}, "aggressive treatment"),
    ({'age': 53, 'gender': 'female', 'symptoms': ['headache', 'fatigue'], 'medical_history': ['diabetes'], 'vital_signs': {'blood_pressure': '166/87', 'heart_rate': 82, 'temperature': 100.6}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 166, 'heart_rate': 82, 'temperature': 100.6}, "aggressive treatment"),
    ({'age': 62, 'gender': 'female', 'symptoms': ['insomnia', 'mood changes'], 'medical_history': ['allergies'], 'vital_signs': {'blood_pressure': '136/74', 'heart_rate': 68, 'temperature': 99.5}, 'condition_severity': 'mild symptoms that started gradually', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 136, 'heart_rate': 68, 'temperature': 99.5}, "conservative treatment"),
    ({'age': 81, 'gender': 'male', 'symptoms': ['back pain', 'muscle stiffness'], 'medical_history': ['depression'], 'vital_signs': {'blood_pressure': '142/81', 'heart_rate': 80, 'temperature': 100.4}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 142, 'heart_rate': 80, 'temperature': 100.4}, "aggressive treatment"),
    ({'age': 45, 'gender': 'male', 'symptoms': ['insomnia', 'mood changes'], 'medical_history': ['diabetes'], 'vital_signs': {'blood_pressure': '143/102', 'heart_rate': 97, 'temperature': 99.8}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 143, 'heart_rate': 97, 'temperature': 99.8}, "aggressive treatment"),
    ({'age': 49, 'gender': 'male', 'symptoms': ['joint pain', 'swelling'], 'medical_history': ['allergies'], 'vital_signs': {'blood_pressure': '124/64', 'heart_rate': 73, 'temperature': 101.6}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 124, 'heart_rate': 73, 'temperature': 101.6}, "aggressive treatment"),
    ({'age': 59, 'gender': 'female', 'symptoms': ['dizziness', 'weakness'], 'medical_history': ['hypertension'], 'vital_signs': {'blood_pressure': '101/100', 'heart_rate': 87, 'temperature': 101.1}, 'condition_severity': 'mild symptoms that started gradually', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 101, 'heart_rate': 87, 'temperature': 101.1}, "conservative treatment"),
    ({'age': 39, 'gender': 'male', 'symptoms': ['back pain', 'muscle stiffness'], 'medical_history': ['diabetes'], 'vital_signs': {'blood_pressure': '162/73', 'heart_rate': 89, 'temperature': 100.5}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 162, 'heart_rate': 89, 'temperature': 100.5}, "aggressive treatment"),
    ({'age': 76, 'gender': 'female', 'symptoms': ['rash', 'itching'], 'medical_history': ['arthritis'], 'vital_signs': {'blood_pressure': '143/76', 'heart_rate': 113, 'temperature': 97.4}, 'condition_severity': 'mild symptoms that started gradually', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 143, 'heart_rate': 113, 'temperature': 97.4}, "conservative treatment"),
    ({'age': 47, 'gender': 'female', 'symptoms': ['nausea', 'vomiting', 'abdominal pain'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '165/77', 'heart_rate': 111, 'temperature': 101.3}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 3, 'history_count': 2, 'bp_systolic': 165, 'heart_rate': 111, 'temperature': 101.3}, "aggressive treatment"),
    ({'age': 21, 'gender': 'male', 'symptoms': ['dizziness', 'weakness'], 'medical_history': ['arthritis'], 'vital_signs': {'blood_pressure': '167/73', 'heart_rate': 105, 'temperature': 98.7}, 'condition_severity': 'chronic symptoms with recent exacerbation', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 167, 'heart_rate': 105, 'temperature': 98.7}, "conservative treatment"),
    ({'age': 73, 'gender': 'female', 'symptoms': ['insomnia', 'mood changes'], 'medical_history': ['depression'], 'vital_signs': {'blood_pressure': '150/95', 'heart_rate': 93, 'temperature': 98.7}, 'condition_severity': 'chronic symptoms with recent exacerbation', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 150, 'heart_rate': 93, 'temperature': 98.7}, "aggressive treatment"),
    ({'age': 20, 'gender': 'male', 'symptoms': ['anxiety', 'palpitations'], 'medical_history': ['hypertension'], 'vital_signs': {'blood_pressure': '137/97', 'heart_rate': 95, 'temperature': 97.7}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 137, 'heart_rate': 95, 'temperature': 97.7}, "conservative treatment"),
    ({'age': 26, 'gender': 'female', 'symptoms': ['anxiety', 'palpitations'], 'medical_history': ['allergies'], 'vital_signs': {'blood_pressure': '176/94', 'heart_rate': 81, 'temperature': 101.7}, 'condition_severity': 'mild symptoms that started gradually', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 176, 'heart_rate': 81, 'temperature': 101.7}, "conservative treatment"),
    ({'age': 45, 'gender': 'male', 'symptoms': ['headache', 'fatigue'], 'medical_history': ['diabetes'], 'vital_signs': {'blood_pressure': '180/100', 'heart_rate': 63, 'temperature': 98.1}, 'condition_severity': 'mild symptoms that started gradually', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 180, 'heart_rate': 63, 'temperature': 98.1}, "conservative treatment"),
    ({'age': 63, 'gender': 'male', 'symptoms': ['dizziness', 'weakness'], 'medical_history': ['depression'], 'vital_signs': {'blood_pressure': '137/87', 'heart_rate': 69, 'temperature': 98.2}, 'condition_severity': 'worsening symptoms over the past week', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 137, 'heart_rate': 69, 'temperature': 98.2}, "conservative treatment"),
    ({'age': 44, 'gender': 'female', 'symptoms': ['fever', 'cough', 'sore throat'], 'medical_history': ['diabetes'], 'vital_signs': {'blood_pressure': '126/92', 'heart_rate': 102, 'temperature': 100.2}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 126, 'heart_rate': 102, 'temperature': 100.2}, "aggressive treatment"),
    ({'age': 83, 'gender': 'male', 'symptoms': ['back pain', 'muscle stiffness'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '147/110', 'heart_rate': 61, 'temperature': 97.5}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 147, 'heart_rate': 61, 'temperature': 97.5}, "aggressive treatment"),
    ({'age': 31, 'gender': 'female', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': ['allergies'], 'vital_signs': {'blood_pressure': '136/100', 'heart_rate': 117, 'temperature': 101.1}, 'condition_severity': 'chronic symptoms with recent exacerbation', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 136, 'heart_rate': 117, 'temperature': 101.1}, "aggressive treatment"),
    ({'age': 18, 'gender': 'female', 'symptoms': ['nausea', 'vomiting', 'abdominal pain'], 'medical_history': ['heart disease'], 'vital_signs': {'blood_pressure': '107/107', 'heart_rate': 66, 'temperature': 100.4}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 107, 'heart_rate': 66, 'temperature': 100.4}, "aggressive treatment"),
    ({'age': 59, 'gender': 'female', 'symptoms': ['rash', 'itching'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '150/75', 'heart_rate': 89, 'temperature': 99.8}, 'condition_severity': 'worsening symptoms over the past week', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 150, 'heart_rate': 89, 'temperature': 99.8}, "aggressive treatment"),
    ({'age': 54, 'gender': 'female', 'symptoms': ['nausea', 'vomiting', 'abdominal pain'], 'medical_history': ['arthritis'], 'vital_signs': {'blood_pressure': '140/68', 'heart_rate': 102, 'temperature': 100.2}, 'condition_severity': 'worsening symptoms over the past week', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 140, 'heart_rate': 102, 'temperature': 100.2}, "aggressive treatment"),
    ({'age': 39, 'gender': 'male', 'symptoms': ['anxiety', 'palpitations'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '107/87', 'heart_rate': 71, 'temperature': 98.4}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 107, 'heart_rate': 71, 'temperature': 98.4}, "conservative treatment"),
    ({'age': 54, 'gender': 'female', 'symptoms': ['rash', 'itching'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '108/76', 'heart_rate': 68, 'temperature': 98.2}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 108, 'heart_rate': 68, 'temperature': 98.2}, "aggressive treatment"),
    ({'age': 85, 'gender': 'male', 'symptoms': ['rash', 'itching'], 'medical_history': [], 'vital_signs': {'blood_pressure': '114/76', 'heart_rate': 62, 'temperature': 100.5}, 'condition_severity': 'mild symptoms that started gradually', 'symptom_count': 2, 'history_count': 0, 'bp_systolic': 114, 'heart_rate': 62, 'temperature': 100.5}, "conservative treatment"),
    ({'age': 58, 'gender': 'female', 'symptoms': ['nausea', 'vomiting', 'abdominal pain'], 'medical_history': ['allergies'], 'vital_signs': {'blood_pressure': '151/66', 'heart_rate': 75, 'temperature': 98.9}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 151, 'heart_rate': 75, 'temperature': 98.9}, "aggressive treatment"),
    ({'age': 42, 'gender': 'female', 'symptoms': ['back pain', 'muscle stiffness'], 'medical_history': ['heart disease'], 'vital_signs': {'blood_pressure': '141/63', 'heart_rate': 70, 'temperature': 98.9}, 'condition_severity': 'worsening symptoms over the past week', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 141, 'heart_rate': 70, 'temperature': 98.9}, "conservative treatment"),
    ({'age': 83, 'gender': 'female', 'symptoms': ['fever', 'cough', 'sore throat'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '147/76', 'heart_rate': 108, 'temperature': 98.2}, 'condition_severity': 'chronic symptoms with recent exacerbation', 'symptom_count': 3, 'history_count': 2, 'bp_systolic': 147, 'heart_rate': 108, 'temperature': 98.2}, "aggressive treatment"),
    ({'age': 40, 'gender': 'female', 'symptoms': ['nausea', 'vomiting', 'abdominal pain'], 'medical_history': ['heart disease', 'high cholesterol'], 'vital_signs': {'blood_pressure': '178/72', 'heart_rate': 105, 'temperature': 98.6}, 'condition_severity': 'chronic symptoms with recent exacerbation', 'symptom_count': 3, 'history_count': 2, 'bp_systolic': 178, 'heart_rate': 105, 'temperature': 98.6}, "aggressive treatment"),
    ({'age': 39, 'gender': 'female', 'symptoms': ['dizziness', 'weakness'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '122/102', 'heart_rate': 60, 'temperature': 101.5}, 'condition_severity': 'worsening symptoms over the past week', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 122, 'heart_rate': 60, 'temperature': 101.5}, "aggressive treatment"),
    ({'age': 29, 'gender': 'male', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': ['hypertension'], 'vital_signs': {'blood_pressure': '93/75', 'heart_rate': 72, 'temperature': 101.2}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 93, 'heart_rate': 72, 'temperature': 101.2}, "aggressive treatment"),
    ({'age': 32, 'gender': 'male', 'symptoms': ['back pain', 'muscle stiffness'], 'medical_history': ['heart disease', 'high cholesterol'], 'vital_signs': {'blood_pressure': '161/98', 'heart_rate': 80, 'temperature': 101.8}, 'condition_severity': 'worsening symptoms over the past week', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 161, 'heart_rate': 80, 'temperature': 101.8}, "aggressive treatment"),
    ({'age': 57, 'gender': 'female', 'symptoms': ['dizziness', 'weakness'], 'medical_history': ['allergies'], 'vital_signs': {'blood_pressure': '160/62', 'heart_rate': 89, 'temperature': 97.4}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 160, 'heart_rate': 89, 'temperature': 97.4}, "aggressive treatment"),
    ({'age': 26, 'gender': 'male', 'symptoms': ['fever', 'cough', 'sore throat'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '156/101', 'heart_rate': 88, 'temperature': 101.6}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 3, 'history_count': 2, 'bp_systolic': 156, 'heart_rate': 88, 'temperature': 101.6}, "aggressive treatment"),
    ({'age': 52, 'gender': 'male', 'symptoms': ['dizziness', 'weakness'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '117/94', 'heart_rate': 68, 'temperature': 100.6}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 117, 'heart_rate': 68, 'temperature': 100.6}, "aggressive treatment"),
    ({'age': 54, 'gender': 'female', 'symptoms': ['insomnia', 'mood changes'], 'medical_history': [], 'vital_signs': {'blood_pressure': '173/80', 'heart_rate': 89, 'temperature': 99.2}, 'condition_severity': 'chronic symptoms with recent exacerbation', 'symptom_count': 2, 'history_count': 0, 'bp_systolic': 173, 'heart_rate': 89, 'temperature': 99.2}, "conservative treatment"),
    ({'age': 31, 'gender': 'male', 'symptoms': ['headache', 'fatigue'], 'medical_history': ['diabetes'], 'vital_signs': {'blood_pressure': '117/74', 'heart_rate': 92, 'temperature': 100.0}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 117, 'heart_rate': 92, 'temperature': 100.0}, "aggressive treatment"),
    ({'age': 76, 'gender': 'female', 'symptoms': ['headache', 'fatigue'], 'medical_history': ['diabetes'], 'vital_signs': {'blood_pressure': '119/103', 'heart_rate': 113, 'temperature': 101.3}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 119, 'heart_rate': 113, 'temperature': 101.3}, "aggressive treatment"),
    ({'age': 27, 'gender': 'female', 'symptoms': ['headache', 'fatigue'], 'medical_history': ['depression'], 'vital_signs': {'blood_pressure': '116/103', 'heart_rate': 75, 'temperature': 100.3}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 116, 'heart_rate': 75, 'temperature': 100.3}, "aggressive treatment"),
    ({'age': 45, 'gender': 'male', 'symptoms': ['fever', 'cough', 'sore throat'], 'medical_history': ['arthritis'], 'vital_signs': {'blood_pressure': '103/97', 'heart_rate': 61, 'temperature': 101.6}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 103, 'heart_rate': 61, 'temperature': 101.6}, "aggressive treatment"),
    ({'age': 31, 'gender': 'male', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '111/104', 'heart_rate': 79, 'temperature': 101.5}, 'condition_severity': 'mild symptoms that started gradually', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 111, 'heart_rate': 79, 'temperature': 101.5}, "aggressive treatment"),
    ({'age': 73, 'gender': 'female', 'symptoms': ['fever', 'cough', 'sore throat'], 'medical_history': ['diabetes'], 'vital_signs': {'blood_pressure': '138/62', 'heart_rate': 114, 'temperature': 99.4}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 138, 'heart_rate': 114, 'temperature': 99.4}, "aggressive treatment"),
    ({'age': 21, 'gender': 'male', 'symptoms': ['nausea', 'vomiting', 'abdominal pain'], 'medical_history': ['arthritis'], 'vital_signs': {'blood_pressure': '174/65', 'heart_rate': 70, 'temperature': 98.2}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 174, 'heart_rate': 70, 'temperature': 98.2}, "aggressive treatment"),
    ({'age': 45, 'gender': 'female', 'symptoms': ['nausea', 'vomiting', 'abdominal pain'], 'medical_history': ['allergies'], 'vital_signs': {'blood_pressure': '95/80', 'heart_rate': 107, 'temperature': 99.4}, 'condition_severity': 'worsening symptoms over the past week', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 95, 'heart_rate': 107, 'temperature': 99.4}, "aggressive treatment"),
    ({'age': 54, 'gender': 'female', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': [], 'vital_signs': {'blood_pressure': '171/70', 'heart_rate': 94, 'temperature': 100.6}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 2, 'history_count': 0, 'bp_systolic': 171, 'heart_rate': 94, 'temperature': 100.6}, "aggressive treatment"),
    ({'age': 76, 'gender': 'male', 'symptoms': ['back pain', 'muscle stiffness'], 'medical_history': ['depression'], 'vital_signs': {'blood_pressure': '113/91', 'heart_rate': 73, 'temperature': 98.8}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 113, 'heart_rate': 73, 'temperature': 98.8}, "aggressive treatment"),
    ({'age': 56, 'gender': 'female', 'symptoms': ['dizziness', 'weakness'], 'medical_history': ['arthritis'], 'vital_signs': {'blood_pressure': '122/74', 'heart_rate': 67, 'temperature': 100.6}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 122, 'heart_rate': 67, 'temperature': 100.6}, "aggressive treatment"),
    ({'age': 32, 'gender': 'male', 'symptoms': ['headache', 'fatigue'], 'medical_history': ['heart disease', 'high cholesterol'], 'vital_signs': {'blood_pressure': '91/65', 'heart_rate': 119, 'temperature': 100.8}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 91, 'heart_rate': 119, 'temperature': 100.8}, "aggressive treatment"),
    ({'age': 27, 'gender': 'female', 'symptoms': ['insomnia', 'mood changes'], 'medical_history': [], 'vital_signs': {'blood_pressure': '174/91', 'heart_rate': 115, 'temperature': 97.7}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 0, 'bp_systolic': 174, 'heart_rate': 115, 'temperature': 97.7}, "aggressive treatment"),
    ({'age': 73, 'gender': 'female', 'symptoms': ['rash', 'itching'], 'medical_history': ['heart disease'], 'vital_signs': {'blood_pressure': '102/66', 'heart_rate': 102, 'temperature': 99.2}, 'condition_severity': 'worsening symptoms over the past week', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 102, 'heart_rate': 102, 'temperature': 99.2}, "aggressive treatment"),
    ({'age': 68, 'gender': 'male', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '105/101', 'heart_rate': 113, 'temperature': 97.8}, 'condition_severity': 'chronic symptoms with recent exacerbation', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 105, 'heart_rate': 113, 'temperature': 97.8}, "aggressive treatment"),
    ({'age': 53, 'gender': 'female', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': ['heart disease'], 'vital_signs': {'blood_pressure': '137/78', 'heart_rate': 70, 'temperature': 99.2}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 137, 'heart_rate': 70, 'temperature': 99.2}, "aggressive treatment"),
    ({'age': 63, 'gender': 'female', 'symptoms': ['nausea', 'vomiting', 'abdominal pain'], 'medical_history': ['arthritis'], 'vital_signs': {'blood_pressure': '146/64', 'heart_rate': 105, 'temperature': 98.4}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 146, 'heart_rate': 105, 'temperature': 98.4}, "aggressive treatment"),
    ({'age': 77, 'gender': 'female', 'symptoms': ['nausea', 'vomiting', 'abdominal pain'], 'medical_history': ['heart disease'], 'vital_signs': {'blood_pressure': '93/102', 'heart_rate': 72, 'temperature': 99.0}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 93, 'heart_rate': 72, 'temperature': 99.0}, "aggressive treatment"),
    ({'age': 25, 'gender': 'male', 'symptoms': ['rash', 'itching'], 'medical_history': ['arthritis'], 'vital_signs': {'blood_pressure': '148/100', 'heart_rate': 113, 'temperature': 98.8}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 148, 'heart_rate': 113, 'temperature': 98.8}, "aggressive treatment"),
    ({'age': 80, 'gender': 'male', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': ['hypertension'], 'vital_signs': {'blood_pressure': '141/106', 'heart_rate': 81, 'temperature': 101.0}, 'condition_severity': 'mild symptoms that started gradually', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 141, 'heart_rate': 81, 'temperature': 101.0}, "aggressive treatment"),
    ({'age': 21, 'gender': 'female', 'symptoms': ['nausea', 'vomiting', 'abdominal pain'], 'medical_history': ['asthma'], 'vital_signs': {'blood_pressure': '179/93', 'heart_rate': 89, 'temperature': 97.3}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 179, 'heart_rate': 89, 'temperature': 97.3}, "conservative treatment"),
    ({'age': 27, 'gender': 'female', 'symptoms': ['rash', 'itching'], 'medical_history': ['asthma'], 'vital_signs': {'blood_pressure': '115/68', 'heart_rate': 110, 'temperature': 99.7}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 115, 'heart_rate': 110, 'temperature': 99.7}, "aggressive treatment"),
    ({'age': 77, 'gender': 'female', 'symptoms': ['anxiety', 'palpitations'], 'medical_history': ['heart disease', 'high cholesterol'], 'vital_signs': {'blood_pressure': '138/89', 'heart_rate': 119, 'temperature': 98.6}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 138, 'heart_rate': 119, 'temperature': 98.6}, "aggressive treatment"),
    ({'age': 81, 'gender': 'male', 'symptoms': ['headache', 'fatigue'], 'medical_history': [], 'vital_signs': {'blood_pressure': '120/105', 'heart_rate': 70, 'temperature': 98.6}, 'condition_severity': 'mild symptoms that started gradually', 'symptom_count': 2, 'history_count': 0, 'bp_systolic': 120, 'heart_rate': 70, 'temperature': 98.6}, "conservative treatment"),
    ({'age': 60, 'gender': 'female', 'symptoms': ['back pain', 'muscle stiffness'], 'medical_history': ['hypertension'], 'vital_signs': {'blood_pressure': '116/77', 'heart_rate': 95, 'temperature': 97.7}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 116, 'heart_rate': 95, 'temperature': 97.7}, "aggressive treatment"),
    ({'age': 65, 'gender': 'female', 'symptoms': ['dizziness', 'weakness'], 'medical_history': ['allergies'], 'vital_signs': {'blood_pressure': '179/106', 'heart_rate': 110, 'temperature': 99.8}, 'condition_severity': 'chronic symptoms with recent exacerbation', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 179, 'heart_rate': 110, 'temperature': 99.8}, "aggressive treatment"),
    ({'age': 38, 'gender': 'male', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': [], 'vital_signs': {'blood_pressure': '138/99', 'heart_rate': 103, 'temperature': 98.2}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 0, 'bp_systolic': 138, 'heart_rate': 103, 'temperature': 98.2}, "aggressive treatment"),
    ({'age': 48, 'gender': 'female', 'symptoms': ['back pain', 'muscle stiffness'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '128/97', 'heart_rate': 87, 'temperature': 98.5}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 128, 'heart_rate': 87, 'temperature': 98.5}, "aggressive treatment"),
    ({'age': 60, 'gender': 'male', 'symptoms': ['anxiety', 'palpitations'], 'medical_history': ['arthritis'], 'vital_signs': {'blood_pressure': '174/66', 'heart_rate': 120, 'temperature': 101.4}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 174, 'heart_rate': 120, 'temperature': 101.4}, "aggressive treatment"),
    ({'age': 42, 'gender': 'male', 'symptoms': ['anxiety', 'palpitations'], 'medical_history': ['heart disease'], 'vital_signs': {'blood_pressure': '172/69', 'heart_rate': 118, 'temperature': 98.3}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 172, 'heart_rate': 118, 'temperature': 98.3}, "aggressive treatment"),
    ({'age': 71, 'gender': 'female', 'symptoms': ['fever', 'cough', 'sore throat'], 'medical_history': [], 'vital_signs': {'blood_pressure': '158/61', 'heart_rate': 118, 'temperature': 99.0}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 3, 'history_count': 0, 'bp_systolic': 158, 'heart_rate': 118, 'temperature': 99.0}, "aggressive treatment"),
    ({'age': 40, 'gender': 'male', 'symptoms': ['headache', 'fatigue'], 'medical_history': ['heart disease', 'high cholesterol'], 'vital_signs': {'blood_pressure': '127/104', 'heart_rate': 120, 'temperature': 97.6}, 'condition_severity': 'worsening symptoms over the past week', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 127, 'heart_rate': 120, 'temperature': 97.6}, "aggressive treatment"),
    ({'age': 56, 'gender': 'male', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': ['arthritis'], 'vital_signs': {'blood_pressure': '147/75', 'heart_rate': 108, 'temperature': 99.3}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 147, 'heart_rate': 108, 'temperature': 99.3}, "aggressive treatment"),
    ({'age': 58, 'gender': 'female', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': ['heart disease'], 'vital_signs': {'blood_pressure': '118/64', 'heart_rate': 81, 'temperature': 97.1}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 118, 'heart_rate': 81, 'temperature': 97.1}, "aggressive treatment"),
    ({'age': 32, 'gender': 'female', 'symptoms': ['insomnia', 'mood changes'], 'medical_history': ['heart disease'], 'vital_signs': {'blood_pressure': '179/84', 'heart_rate': 91, 'temperature': 99.0}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 179, 'heart_rate': 91, 'temperature': 99.0}, "conservative treatment"),
    ({'age': 19, 'gender': 'female', 'symptoms': ['anxiety', 'palpitations'], 'medical_history': ['allergies'], 'vital_signs': {'blood_pressure': '174/83', 'heart_rate': 64, 'temperature': 99.5}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 174, 'heart_rate': 64, 'temperature': 99.5}, "aggressive treatment"),
    ({'age': 60, 'gender': 'female', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': ['depression'], 'vital_signs': {'blood_pressure': '176/94', 'heart_rate': 84, 'temperature': 101.8}, 'condition_severity': 'chronic symptoms with recent exacerbation', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 176, 'heart_rate': 84, 'temperature': 101.8}, "aggressive treatment"),
    ({'age': 46, 'gender': 'male', 'symptoms': ['headache', 'fatigue'], 'medical_history': ['arthritis'], 'vital_signs': {'blood_pressure': '146/62', 'heart_rate': 97, 'temperature': 98.8}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 146, 'heart_rate': 97, 'temperature': 98.8}, "conservative treatment"),
    ({'age': 78, 'gender': 'male', 'symptoms': ['insomnia', 'mood changes'], 'medical_history': [], 'vital_signs': {'blood_pressure': '128/85', 'heart_rate': 95, 'temperature': 101.2}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 0, 'bp_systolic': 128, 'heart_rate': 95, 'temperature': 101.2}, "aggressive treatment"),
    ({'age': 70, 'gender': 'female', 'symptoms': ['headache', 'fatigue'], 'medical_history': ['asthma'], 'vital_signs': {'blood_pressure': '154/97', 'heart_rate': 81, 'temperature': 101.3}, 'condition_severity': 'worsening symptoms over the past week', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 154, 'heart_rate': 81, 'temperature': 101.3}, "aggressive treatment"),
    ({'age': 64, 'gender': 'male', 'symptoms': ['dizziness', 'weakness'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '127/107', 'heart_rate': 115, 'temperature': 98.7}, 'condition_severity': 'mild symptoms that started gradually', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 127, 'heart_rate': 115, 'temperature': 98.7}, "conservative treatment"),
    ({'age': 23, 'gender': 'male', 'symptoms': ['insomnia', 'mood changes'], 'medical_history': ['diabetes'], 'vital_signs': {'blood_pressure': '176/75', 'heart_rate': 85, 'temperature': 97.6}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 176, 'heart_rate': 85, 'temperature': 97.6}, "aggressive treatment"),
    ({'age': 21, 'gender': 'male', 'symptoms': ['fever', 'cough', 'sore throat'], 'medical_history': ['allergies'], 'vital_signs': {'blood_pressure': '166/64', 'heart_rate': 84, 'temperature': 98.9}, 'condition_severity': 'worsening symptoms over the past week', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 166, 'heart_rate': 84, 'temperature': 98.9}, "conservative treatment"),
    ({'age': 62, 'gender': 'female', 'symptoms': ['back pain', 'muscle stiffness'], 'medical_history': ['diabetes'], 'vital_signs': {'blood_pressure': '177/74', 'heart_rate': 119, 'temperature': 98.3}, 'condition_severity': 'chronic symptoms with recent exacerbation', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 177, 'heart_rate': 119, 'temperature': 98.3}, "aggressive treatment"),
    ({'age': 20, 'gender': 'female', 'symptoms': ['fever', 'cough', 'sore throat'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '113/63', 'heart_rate': 76, 'temperature': 98.9}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 3, 'history_count': 2, 'bp_systolic': 113, 'heart_rate': 76, 'temperature': 98.9}, "conservative treatment"),
    ({'age': 62, 'gender': 'female', 'symptoms': ['dizziness', 'weakness'], 'medical_history': ['heart disease', 'high cholesterol'], 'vital_signs': {'blood_pressure': '159/91', 'heart_rate': 88, 'temperature': 97.4}, 'condition_severity': 'mild symptoms that started gradually', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 159, 'heart_rate': 88, 'temperature': 97.4}, "conservative treatment"),
    ({'age': 60, 'gender': 'female', 'symptoms': ['headache', 'fatigue'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '158/67', 'heart_rate': 119, 'temperature': 98.9}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 158, 'heart_rate': 119, 'temperature': 98.9}, "aggressive treatment"),
    ({'age': 64, 'gender': 'female', 'symptoms': ['insomnia', 'mood changes'], 'medical_history': ['heart disease'], 'vital_signs': {'blood_pressure': '180/64', 'heart_rate': 62, 'temperature': 100.3}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 180, 'heart_rate': 62, 'temperature': 100.3}, "aggressive treatment"),
    ({'age': 20, 'gender': 'female', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': ['heart disease', 'high cholesterol'], 'vital_signs': {'blood_pressure': '106/68', 'heart_rate': 102, 'temperature': 99.4}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 106, 'heart_rate': 102, 'temperature': 99.4}, "aggressive treatment"),
    ({'age': 71, 'gender': 'female', 'symptoms': ['headache', 'fatigue'], 'medical_history': ['arthritis'], 'vital_signs': {'blood_pressure': '154/108', 'heart_rate': 71, 'temperature': 99.5}, 'condition_severity': 'mild symptoms that started gradually', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 154, 'heart_rate': 71, 'temperature': 99.5}, "conservative treatment"),
    ({'age': 25, 'gender': 'female', 'symptoms': ['nausea', 'vomiting', 'abdominal pain'], 'medical_history': ['heart disease'], 'vital_signs': {'blood_pressure': '108/61', 'heart_rate': 62, 'temperature': 98.2}, 'condition_severity': 'worsening symptoms over the past week', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 108, 'heart_rate': 62, 'temperature': 98.2}, "conservative treatment"),
    ({'age': 48, 'gender': 'female', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': ['heart disease'], 'vital_signs': {'blood_pressure': '105/95', 'heart_rate': 108, 'temperature': 99.1}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 105, 'heart_rate': 108, 'temperature': 99.1}, "aggressive treatment"),
    ({'age': 28, 'gender': 'male', 'symptoms': ['dizziness', 'weakness'], 'medical_history': ['asthma'], 'vital_signs': {'blood_pressure': '146/95', 'heart_rate': 105, 'temperature': 99.1}, 'condition_severity': 'mild symptoms that started gradually', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 146, 'heart_rate': 105, 'temperature': 99.1}, "conservative treatment"),
    ({'age': 19, 'gender': 'male', 'symptoms': ['dizziness', 'weakness'], 'medical_history': [], 'vital_signs': {'blood_pressure': '162/78', 'heart_rate': 88, 'temperature': 97.6}, 'condition_severity': 'chronic symptoms with recent exacerbation', 'symptom_count': 2, 'history_count': 0, 'bp_systolic': 162, 'heart_rate': 88, 'temperature': 97.6}, "conservative treatment"),
    ({'age': 31, 'gender': 'female', 'symptoms': ['joint pain', 'swelling'], 'medical_history': ['heart disease', 'high cholesterol'], 'vital_signs': {'blood_pressure': '149/86', 'heart_rate': 63, 'temperature': 98.0}, 'condition_severity': 'worsening symptoms over the past week', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 149, 'heart_rate': 63, 'temperature': 98.0}, "conservative treatment"),
    ({'age': 83, 'gender': 'male', 'symptoms': ['insomnia', 'mood changes'], 'medical_history': ['diabetes'], 'vital_signs': {'blood_pressure': '120/100', 'heart_rate': 103, 'temperature': 101.6}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 120, 'heart_rate': 103, 'temperature': 101.6}, "aggressive treatment"),
    ({'age': 78, 'gender': 'female', 'symptoms': ['anxiety', 'palpitations'], 'medical_history': ['heart disease'], 'vital_signs': {'blood_pressure': '177/80', 'heart_rate': 113, 'temperature': 100.8}, 'condition_severity': 'mild symptoms that started gradually', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 177, 'heart_rate': 113, 'temperature': 100.8}, "conservative treatment"),
    ({'age': 69, 'gender': 'male', 'symptoms': ['rash', 'itching'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '99/96', 'heart_rate': 100, 'temperature': 100.4}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 99, 'heart_rate': 100, 'temperature': 100.4}, "aggressive treatment"),
    ({'age': 70, 'gender': 'male', 'symptoms': ['dizziness', 'weakness'], 'medical_history': ['heart disease'], 'vital_signs': {'blood_pressure': '97/97', 'heart_rate': 107, 'temperature': 99.7}, 'condition_severity': 'chronic symptoms with recent exacerbation', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 97, 'heart_rate': 107, 'temperature': 99.7}, "aggressive treatment"),
    ({'age': 35, 'gender': 'male', 'symptoms': ['nausea', 'vomiting', 'abdominal pain'], 'medical_history': ['heart disease'], 'vital_signs': {'blood_pressure': '151/77', 'heart_rate': 106, 'temperature': 99.9}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 151, 'heart_rate': 106, 'temperature': 99.9}, "aggressive treatment"),
    ({'age': 85, 'gender': 'male', 'symptoms': ['nausea', 'vomiting', 'abdominal pain'], 'medical_history': ['asthma'], 'vital_signs': {'blood_pressure': '112/86', 'heart_rate': 61, 'temperature': 97.9}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 112, 'heart_rate': 61, 'temperature': 97.9}, "aggressive treatment"),
    ({'age': 42, 'gender': 'male', 'symptoms': ['anxiety', 'palpitations'], 'medical_history': ['arthritis'], 'vital_signs': {'blood_pressure': '168/94', 'heart_rate': 109, 'temperature': 99.4}, 'condition_severity': 'worsening symptoms over the past week', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 168, 'heart_rate': 109, 'temperature': 99.4}, "aggressive treatment"),
]

medical_test_data = [
    ({'age': 52, 'gender': 'male', 'symptoms': ['dizziness', 'weakness'], 'medical_history': ['heart disease'], 'vital_signs': {'blood_pressure': '136/71', 'heart_rate': 79, 'temperature': 97.1}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 136, 'heart_rate': 79, 'temperature': 97.1}, "aggressive treatment"),
    ({'age': 76, 'gender': 'female', 'symptoms': ['fever', 'cough', 'sore throat'], 'medical_history': ['heart disease'], 'vital_signs': {'blood_pressure': '133/66', 'heart_rate': 65, 'temperature': 98.9}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 133, 'heart_rate': 65, 'temperature': 98.9}, "aggressive treatment"),
    ({'age': 84, 'gender': 'male', 'symptoms': ['insomnia', 'mood changes'], 'medical_history': ['allergies'], 'vital_signs': {'blood_pressure': '151/60', 'heart_rate': 120, 'temperature': 98.8}, 'condition_severity': 'worsening symptoms over the past week', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 151, 'heart_rate': 120, 'temperature': 98.8}, "aggressive treatment"),
    ({'age': 51, 'gender': 'male', 'symptoms': ['insomnia', 'mood changes'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '154/93', 'heart_rate': 70, 'temperature': 97.3}, 'condition_severity': 'acute onset with significant distress', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 154, 'heart_rate': 70, 'temperature': 97.3}, "aggressive treatment"),
    ({'age': 61, 'gender': 'male', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '134/97', 'heart_rate': 79, 'temperature': 100.2}, 'condition_severity': 'worsening symptoms over the past week', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 134, 'heart_rate': 79, 'temperature': 100.2}, "aggressive treatment"),
    ({'age': 59, 'gender': 'male', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': ['heart disease', 'high cholesterol'], 'vital_signs': {'blood_pressure': '124/109', 'heart_rate': 101, 'temperature': 98.7}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 124, 'heart_rate': 101, 'temperature': 98.7}, "aggressive treatment"),
    ({'age': 33, 'gender': 'female', 'symptoms': ['nausea', 'vomiting', 'abdominal pain'], 'medical_history': [], 'vital_signs': {'blood_pressure': '135/74', 'heart_rate': 100, 'temperature': 98.0}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 3, 'history_count': 0, 'bp_systolic': 135, 'heart_rate': 100, 'temperature': 98.0}, "conservative treatment"),
    ({'age': 18, 'gender': 'female', 'symptoms': ['back pain', 'muscle stiffness'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '146/81', 'heart_rate': 71, 'temperature': 101.8}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 146, 'heart_rate': 71, 'temperature': 101.8}, "aggressive treatment"),
    ({'age': 34, 'gender': 'female', 'symptoms': ['headache', 'fatigue'], 'medical_history': ['asthma'], 'vital_signs': {'blood_pressure': '142/101', 'heart_rate': 69, 'temperature': 97.4}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 142, 'heart_rate': 69, 'temperature': 97.4}, "aggressive treatment"),
    ({'age': 59, 'gender': 'female', 'symptoms': ['rash', 'itching'], 'medical_history': ['depression'], 'vital_signs': {'blood_pressure': '141/104', 'heart_rate': 78, 'temperature': 99.8}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 141, 'heart_rate': 78, 'temperature': 99.8}, "conservative treatment"),
    ({'age': 55, 'gender': 'female', 'symptoms': ['anxiety', 'palpitations'], 'medical_history': ['hypertension'], 'vital_signs': {'blood_pressure': '156/72', 'heart_rate': 65, 'temperature': 98.2}, 'condition_severity': 'worsening symptoms over the past week', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 156, 'heart_rate': 65, 'temperature': 98.2}, "conservative treatment"),
    ({'age': 68, 'gender': 'male', 'symptoms': ['nausea', 'vomiting', 'abdominal pain'], 'medical_history': ['allergies'], 'vital_signs': {'blood_pressure': '161/83', 'heart_rate': 65, 'temperature': 101.0}, 'condition_severity': 'mild symptoms that started gradually', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 161, 'heart_rate': 65, 'temperature': 101.0}, "conservative treatment"),
    ({'age': 62, 'gender': 'female', 'symptoms': ['headache', 'fatigue'], 'medical_history': ['allergies'], 'vital_signs': {'blood_pressure': '125/60', 'heart_rate': 96, 'temperature': 101.3}, 'condition_severity': 'chronic symptoms with recent exacerbation', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 125, 'heart_rate': 96, 'temperature': 101.3}, "aggressive treatment"),
    ({'age': 52, 'gender': 'female', 'symptoms': ['anxiety', 'palpitations'], 'medical_history': ['hypertension'], 'vital_signs': {'blood_pressure': '174/94', 'heart_rate': 89, 'temperature': 99.1}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 174, 'heart_rate': 89, 'temperature': 99.1}, "aggressive treatment"),
    ({'age': 23, 'gender': 'male', 'symptoms': ['rash', 'itching'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '178/98', 'heart_rate': 90, 'temperature': 98.5}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 178, 'heart_rate': 90, 'temperature': 98.5}, "aggressive treatment"),
    ({'age': 41, 'gender': 'female', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': ['depression'], 'vital_signs': {'blood_pressure': '169/80', 'heart_rate': 102, 'temperature': 101.2}, 'condition_severity': 'chronic symptoms with recent exacerbation', 'symptom_count': 2, 'history_count': 1, 'bp_systolic': 169, 'heart_rate': 102, 'temperature': 101.2}, "aggressive treatment"),
    ({'age': 56, 'gender': 'male', 'symptoms': ['fever', 'cough', 'sore throat'], 'medical_history': ['asthma'], 'vital_signs': {'blood_pressure': '119/84', 'heart_rate': 104, 'temperature': 97.8}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 119, 'heart_rate': 104, 'temperature': 97.8}, "aggressive treatment"),
    ({'age': 64, 'gender': 'male', 'symptoms': ['fever', 'cough', 'sore throat'], 'medical_history': ['depression'], 'vital_signs': {'blood_pressure': '110/94', 'heart_rate': 109, 'temperature': 101.6}, 'condition_severity': 'mild symptoms that started gradually', 'symptom_count': 3, 'history_count': 1, 'bp_systolic': 110, 'heart_rate': 109, 'temperature': 101.6}, "conservative treatment"),
    ({'age': 78, 'gender': 'male', 'symptoms': ['chest pain', 'shortness of breath'], 'medical_history': [], 'vital_signs': {'blood_pressure': '178/100', 'heart_rate': 75, 'temperature': 97.5}, 'condition_severity': 'severe symptoms that started suddenly', 'symptom_count': 2, 'history_count': 0, 'bp_systolic': 178, 'heart_rate': 75, 'temperature': 97.5}, "aggressive treatment"),
    ({'age': 65, 'gender': 'male', 'symptoms': ['headache', 'fatigue'], 'medical_history': ['hypertension', 'diabetes'], 'vital_signs': {'blood_pressure': '169/96', 'heart_rate': 66, 'temperature': 97.4}, 'condition_severity': 'moderate symptoms present for several days', 'symptom_count': 2, 'history_count': 2, 'bp_systolic': 169, 'heart_rate': 66, 'temperature': 97.4}, "aggressive treatment"),
]

def get_medical_training_data():
    """Get medical training data as list of (factors_dict, outcome) tuples."""
    return medical_training_data

def get_medical_test_data():
    """Get medical test data as list of (factors_dict, outcome) tuples."""
    return medical_test_data

def convert_to_decision_contexts(data_list):
    """Convert factor dictionaries to DecisionContext objects."""
    contexts = []
    for factors, outcome in data_list:
        # Create scenario and condition from factors
        scenario = "Decision scenario based on provided factors"
        condition = "Condition derived from factor values"
        outcomes = ["conservative treatment", "aggressive treatment"] if "medical" == "medical" else \
                  ["growth-focused strategy", "income-focused strategy"] if "medical" == "financial" else \
                  ["personalized recommendations", "trending recommendations"]
        
        context = DecisionContext(
            scenario=scenario,
            condition=condition,
            outcomes=outcomes
        )
        contexts.append((context, outcome))
    return contexts
